### ISSUE TITLE
Can't compile in VS 2017: NU1101	Unable to find package Microsoft.Logging.Stubs

### ISSUE THREAD

**Issue by nokola** [Microsoft/Snip-Insights#4]
Repro steps:
1. Open .sln in VS 2017
2. Ctrl+F5

Expected:
compiles and runs

Actual:
Error in VS:
Severity	Code	Description	Project	File	Line	Suppression State Error	NU1101	Unable to find package Microsoft.Logging.Stubs. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, NuGet.org

**Comment by guangw** [comment]
Same error for VS 2015.

**Comment by Mikerr1111** [comment]
Visual Studio(2015 or 2017) and Visual Studio Code should be listed in the installation prerequisites.

**Comment by Mikerr1111** [comment]
[NU1101 Error](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings#nu100)
![nu1101](https://user-images.githubusercontent.com/18353476/39853076-e2b85f5c-53d4-11e8-801b-feaed133154f.PNG)

**Comment by markAtMicrosoft** [comment]
Thank you for reporting the issue and we are looking at it.  I'll post an update as soon as it's available.  Also, Visual Studio 2017 should be the go to IDE for this project.  I'll update the description.

**Comment by markAtMicrosoft** [comment]
The master branch should have this issue resolved now.
