### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by Rod-in-NM** [Microsoft/Snip-Insights#5]
I tried running the `git clone` command from a PowerShell prompt. It failed with the following error:

> Cloning into 'Snip-Insights'...
> fatal: unable to access 'https://github.com/Microsoft/Snip-Insights.git/': SSL certificate problem: self
> signed certificate in certificate chain

Is it me or something else?

**Comment by yihan-us** [comment]
You might want to check out if you have same issue cloning other repositories. This doesn't seem to be related to this particular repository based on my understanding, at least I don't have this issue.

**Comment by Rod-in-NM** [comment]
OK, it must be at my end. I've tried another repo; got the same error. Tony, you may close this issue.

Thanks.
