### ISSUE TITLE
More apps from Microsoft Garage project please!

### ISSUE THREAD

**Issue by JimSEOW** [Microsoft/Snip-Insights#8]
We need ways to feedback new ideas stimulated by following Build 2018 on youtube or channel 9
- Where can I submit new app idea to Microsoft Garage project?
- Where can I get a list of open sourced apps released by a Microsoft Garage project?

**Comment by markAtMicrosoft** [comment]
Hey, if you are looking to provide any feedback or ideas, go to our User Voice site at: https://microsoftgarage.uservoice.com/

To see other Garage Open Source Projects, you could go to our workbench at https://www.microsoft.com/en-us/garage/workbench/, select "Open Source" for the platform and press the Update button.
